export const skills = [
  "Python",
  "Java",
  "C++",
  "C#",
  "JavaScript",
  "HTML",
  "CSS",
  "React",
  "Angular",
  "Vue",
  "Node.js",
  "Express",
  "MongoDB",
  "SQL",
  "NoSQL",
  "Django",
  "Flask",
  "Spring",
  "Hibernate",
  "JPA",
  "JSP",
  "Servlets",
  "JDBC",
  "Swing",
  "JavaFX",
  "Android Development",
  "iOS",
  "Swift",
  "Kotlin",
  "Objective-C",
  "React Native",
  "Flutter",
  "Xamarin",
  "Unity",
  "Unreal Engine",
  "Cocos2d",
  "Phaser",
  "HTML5",
  "CSS3",
  "Bootstrap",
  "Sass",
  "Less",
  "Materialize",
  "Bulma",
  "Foundation",
  "jQuery",
  "Ajax",
  "TypeScript",
  "WebAssembly",
  "WebRTC",
  "WebSockets",
  "Socket.IO",
  "GraphQL",
  "REST",
  "SOAP",
  "OAuth",
  "JWT",
  "Firebase",
  "AWS",
  "Azure",
  "Google Cloud",
  "Heroku",
  "Netlify",
  "Vercel",
  "Docker",
  "Kubernetes",
  "Jenkins",
  "Travis CI",
  "CircleCI",
  "Git",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "Jira",
  "Trello",
  "Asana",
  "Natural Language Processing",
  "Deep Learning",
  "PyTorch",
  "Communication Skills",
  "Verbal Communication",
  "Written Communication",
  "Public Speaking",
  "Active Listening",
  "Negotiation",
  "Storytelling",
  "Cognitive & Thinking Skills",
  "Critical Thinking",
  "Problem-Solving",
  "Decision-Making",
  "Analytical Reasoning",
  "Creativity",
  "Research Skills",
  "Interpersonal Skills",
  "Teamwork",
  "Leadership",
  "Conflict Resolution",
  "Empathy",
  "Networking",
  "Emotional Intelligence",
  "Technical & Digital Skills",
  "Basic Computer Skills",
  "Microsoft Office / Google Workspace",
  "Data Analysis",
  "Programming (Python, Java, etc.)",
  "Web Development",
  "Cybersecurity Basics",
  "Creative Skills",
  "Graphic Design",
  "Writing (Creative/Content)",
  "Video Editing",
  "Photography",
  "Music/Art",
  "Personal Development Skills",
  "Self-Discipline",
  "Adaptability",
  "Stress Management",
  "Goal Setting",
  "Productivity Techniques",
  "Practical / Life Skills",
  "Cooking",
  "Budgeting",
  "First Aid",
  "Driving",
  "Basic Repairs",
  "Mathematics",
  "English",
  "Science",
  "Social Studies",
  "Computer Science",
  "General Knowledge",
  "Art",
  "Physical Education",
  "Environmental Studies",
  "Hindi",
  "Telugu",
];
