export const skills = [
  // Programming Languages
  "Python",
  "JavaScript",
  "Java",
  "C++",
  "C#",
  "TypeScript",
  "Swift",
  "Kotlin",
  "Go",
  "Rust",
  "Ruby",
  "PHP",
  "R",
  "Scala",
  "Perl",
  "Objective-C",
  "Dart",
  "Lua",

  // Web Development
  "Web Development",
  "HTML",
  "HTML5",
  "CSS",
  "CSS3",
  "React",
  "Angular",
  "Vue",
  "Next.js",
  "Node.js",
  "Express",
  "Django",
  "Flask",
  "Spring",
  "Ruby on Rails",
  "Laravel",
  "WordPress",
  "Bootstrap",
  "Tailwind CSS",
  "Sass",
  "Less",
  "jQuery",
  "Ajax",
  "GraphQL",
  "REST",
  "WebAssembly",
  "WebRTC",
  "WebSockets",
  "Socket.IO",

  // App Development
  "App Development",
  "Android Development",
  "iOS Development",
  "React Native",
  "Flutter",
  "Xamarin",
  "SwiftUI",
  "Jetpack Compose",

  // AI & Machine Learning
  "Artificial Intelligence",
  "Machine Learning",
  "Deep Learning",
  "Natural Language Processing",
  "Computer Vision",
  "TensorFlow",
  "PyTorch",
  "Keras",
  "Scikit-learn",
  "Reinforcement Learning",
  "Neural Networks",
  "ChatGPT / Prompt Engineering",

  // Data Analysis & Data Science
  "Data Analysis",
  "Data Science",
  "Data Visualization",
  "Big Data Analytics",
  "Statistical Analysis",
  "Pandas",
  "NumPy",
  "Matplotlib",
  "Tableau",
  "Power BI",
  "Excel & Spreadsheets",
  "SQL",
  "NoSQL",
  "MongoDB",
  "PostgreSQL",
  "MySQL",
  "Hadoop",
  "Spark",

  // Cybersecurity
  "Cybersecurity",
  "Ethical Hacking",
  "Penetration Testing",
  "Network Security",
  "Information Security",
  "Cryptography",

  // Cloud Computing & DevOps
  "Cloud Computing",
  "AWS",
  "Azure",
  "Google Cloud",
  "Firebase",
  "Docker",
  "Kubernetes",
  "DevOps",
  "CI/CD",
  "Jenkins",
  "Terraform",
  "Ansible",
  "Serverless Architecture",
  "Heroku",
  "Netlify",
  "Vercel",

  // UI/UX Design
  "UI/UX Design",
  "User Interface Design",
  "User Experience Design",
  "Figma",
  "Adobe XD",
  "Sketch",
  "Wireframing",
  "Prototyping",
  "Design Thinking",

  // Digital Marketing
  "Digital Marketing",
  "Social Media Marketing",
  "Search Engine Optimization (SEO)",
  "Content Marketing",
  "Email Marketing",
  "Google Ads",
  "Facebook Ads",
  "Affiliate Marketing",
  "Influencer Marketing",
  "Marketing Strategy",

  // Business & Entrepreneurship
  "Business Strategy",
  "E-commerce Management",
  "Dropshipping",
  "Sales & Negotiation",
  "Project Management",
  "Product Management",
  "Agile & Scrum",
  "Startup Development",
  "Financial Planning",
  "Accounting & Bookkeeping",
  "Stock Market & Trading",
  "Cryptocurrency & Blockchain",

  // Creative Skills
  "Graphic Design",
  "Video Editing",
  "Animation",
  "Motion Graphics",
  "Photography",
  "Photo Editing",
  "Adobe Photoshop",
  "Adobe Illustrator",
  "Adobe Premiere Pro",
  "Adobe After Effects",
  "Canva",
  "3D Modeling",
  "Illustration",
  "Content Writing",
  "Copywriting",
  "Creative Writing",
  "Blog Writing",
  "Technical Writing",
  "Scriptwriting",
  "Music Production",
  "Audio Editing",
  "Podcasting",
  "Voice Over",

  // Communication & Personal Development
  "Public Speaking",
  "Leadership",
  "Negotiation Skills",
  "Time Management",
  "Emotional Intelligence",
  "Critical Thinking",
  "Problem-Solving",
  "Communication Skills",
  "Presentation Skills",
  "Teamwork & Collaboration",
  "Conflict Resolution",
  "Decision Making",
  "Stress Management",
  "Adaptability",

  // Language Skills
  "English Speaking",
  "English Writing",
  "Spanish",
  "French",
  "German",
  "Mandarin Chinese",
  "Japanese",
  "Korean",
  "Arabic",
  "Hindi",
  "Portuguese",
  "Italian",
  "Russian",
  "Turkish",
  "Urdu",
  "Sign Language",

  // Practical & Everyday Skills
  "Cooking & Baking",
  "Fitness Training",
  "Yoga & Meditation",
  "Nutrition & Diet Planning",
  "Financial Management",
  "Personal Finance",
  "DIY Crafting",
  "Sewing & Tailoring",
  "Interior Design",
  "Gardening",
  "Car Maintenance",
  "First Aid & CPR",
  "Event Planning",
  "Parenting Skills",

  // Game Development
  "Game Development",
  "Unity",
  "Unreal Engine",
  "Game Design",

  // Other Tech
  "Git & Version Control",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "Jira",
  "Trello",
  "Asana",
  "Linux Administration",
  "Networking",
  "Database Administration",
  "API Development",
  "Microservices",
  "OAuth",
  "JWT",
  "Blockchain Development",
  "IoT (Internet of Things)",
  "Robotics",
  "Embedded Systems",
  "Automation & Scripting",

  // Education & Training
  "Tutoring",
  "Online Teaching",
  "Curriculum Development",
  "Research Skills",
  "Academic Writing",
  "Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
  "Statistics",
];
